modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "golditemexpansion"
version = "${version}"
displayName = "Gold Item Expansion"
authors = "Saverio, Zhao Zhenxiang"
description = '''
Adds enhanced gold-related items and effects to Minecraft.
'''
#logoFile = ""

[[mixins]]
config="golditemexpansion.forge.mixins.json"

[[dependencies.golditemexpansion]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.golditemexpansion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.golditemexpansion]]
modId = "architectury"
mandatory = true
versionRange = "[10.1.20,)"
ordering = "AFTER"
side = "BOTH"
