modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "golditemexpansion"
version = "${version}"
displayName = "Gold Item Expansion"
authors = "Saverio, Zhao Zhenxiang"
description = '''
Adds enhanced gold-related items and effects to Minecraft.
'''
#logoFile = ""

[[dependencies.golditemexpansion]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.golditemexpansion]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.golditemexpansion]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "golditemexpansion.neoforge.mixins.json"